server:
  port: 8001
spring:
  application:
    name: cloud-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_user?autoReconnect=true&useSSL=false
    username: root
    password: Liuhuzile0301
eureka:
  client:
    register-with-eureka: false # 不注册自己
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:7001/eureka/
mybatis:
    mapperLocations: classpath:mappers/*.xml

