
server:
  port: 7006
spring:
  application:
    name: cloud-gateway
eureka:
  client:
    register-with-eureka: false # 不注册自己
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:7001/eureka/
zuul:
  ignored-services: "*"
  sensitive-headers:
  routes:
      auth:
        path: /auth/**
        serviceId: cloud-auth
      user:
        path: /course/**
        serviceId: cloud-course
