server:
  port: 7002

spring:
  application:
    name: cloud-config
  cloud:
      config:
        server:
          git:
            uri: https://github.com/llldddbbb/cloud-class
            searchPaths: cloud-config-repo

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false # 不注册自己
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
